### ISSUE TITLE
1.0 Release Tracking Issue

### ISSUE THREAD

**Issue by mikeal** [ipfs-shipyard/proto.school#50]
This issue is here to document the scope of the 1.0 release and link to relevant issues.

**THE LIST BELOW IS OUT OF DATE. 1.0 release tracking is now being managed through milestones on GitHub issues. Please visit https://github.com/ipfs-shipyard/proto.school/milestone/1 for current status.**

## Meetups

- [ ] [Document how to start an in-person workshop](https://github.com/ipfs-shipyard/proto.school/issues/51)
~- [ ] Automate the listing of all in-person meetups~
- [ ] Automatically generated calendar - TBD / not targeted for launch
- [ ] Interactive map of all in-person meetups - TBD / not targeted for launch

## Content

- [ ] Learn decentralized data-structures - being tracked in issue #57 
- [ ] Migrate existing lessons to new CID based cbor links. - tracked in issue #79 & PR #88 

## Site Re-Design - see issue #51

- [x] [Logo](https://github.com/ipfs-shipyard/proto.school/issues/52)
- [ ] New site design to support:
  - [ ] list of local chapters see issue #51
  ~- [ ] Lessons broken down by courses~ (future iteration)

## Release Resources - see issue #51

~- [ ] Twitter~ (before public launch but not 1.0)
- [ ] New Org - see issue #51
  - [ ] help repo - see issue #51
  - [ ] organizers repo - see issue #51
~- [ ] Discourse? ~

**Comment by terichadbourne** [comment]
@mikeal Can you tell me more about "lessons broken down by courses"? Does course there refer to the different series of lessons (currently basics and blog) or something else? 

We've received some proposed logo designs from Agata which can be found [here](https://github.com/protocol/design/issues/114#issuecomment-432698459).

**Comment by mikeal** [comment]
@terichadbourne so, the idea was that you would have something like "basics" where we'd put "Learning Decentralized Data-Structures" and then a section for "IPFS" with a sub-section "IPFS - IPLD."

**Comment by terichadbourne** [comment]
@mikeal If I'm understanding you correctly, once we had lots more content than we do now, in addition to exercises inside of lessons inside of workshops, those workshops could be grouped into a bigger category of courses. That sounds like something to add down the road, not something required in our current re-design that adds the community features, right?

**Comment by mikeal** [comment]
yes, exactly :)

**Comment by terichadbourne** [comment]
Updated the checklist to show we now have our logo. The source files can be found here: https://drive.google.com/drive/u/1/folders/1KT62AbG5lH6EVN7f8V_Cih-KBb7bR7Y3

(In the mock-ups of many versions, the one we've chosen is version 3.

**Comment by terichadbourne** [comment]
I will come back and ensure all of these items are captured separately in issues attached to milestones, then close this

**Comment by terichadbourne** [comment]
See issues tagged as 1.0 milestones at https://github.com/ipfs-shipyard/proto.school/milestone/1

**Comment by mikeal** [comment]
@terichadbourne we can cut those, they shouldn't have been targeted for launch. The map in particular is hard to build and pretty useless until we have a lot of chapters signed up :)
